import SideNav from "./SideNav"

export const metadata = {
  title: 'MPSC Blog Admin Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
         <SideNav />
        {children}
        </div>
      </body>
    </html>
  )
}
