import SideNav from "./SideNav";

export const metadata = {
  title: "MPSC Blog Admin Page",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <section className="flex mt-6">
      <SideNav />
      {children}
    </section>
  );
}
