import './globals.css'
import Footer from './components/Footer'

export const metadata = {
  title: 'MPSC Blog Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className='container mx-auto'>
        {children}
        <Footer />
        </body>
    </html>
  )
}
